name: feature branches push

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v3
        env:
          FORCE_COLOR: 0
        with:
          node-version: 20.10.0
          cache: 'npm'
      - run: npm install
      - run: npm run lint
